### ISSUE TITLE
GCP deploy

### ISSUE THREAD

**Issue by faranahmadk** [faranak-cs/rag#11]
### GitHub Connection
- Use Cloud Build to connect your GitHub repo and trigger automated deployments. [here](https://cloud.google.com/build/docs)
### Database
- [Cloud SQL](https://cloud.google.com/sql/docs) (for relational) or
- [Firestore](https://firebase.google.com/docs/firestore) (for NoSQL) are good options within GCP
- [AlloyDB](https://cloud.google.com/alloydb/docs) is great if you need high performance and scalability.
### Storage
- [Cloud Storage](https://cloud.google.com/storage/docs) for static files like images or HTML.
### Secrets
- [Secret Manager](https://cloud.google.com/secret-manager/docs) for securely storing sensitive information.
### App Server
- [App Engine](https://cloud.google.com/appengine/docs), [Cloud Run](https://cloud.google.com/run/docs), or [GKE](https://cloud.google.com/kubernetes-engine/docs) depending on your needs.

**Comment by faranak-cs** [comment]
https://cloud.google.com/run?hl=en

**Comment by faranak-cs** [comment]
https://github.com/faranak-cs/test-cloud-run

**Comment by faranahmadk** [comment]
GCS --> Vertex AI Workbench:
https://cloud.google.com/vertex-ai/docs/workbench/instances/cloud-storage

Troubleshooting:
https://cloud.google.com/vertex-ai/docs/general/troubleshooting-workbench?component=any#instances
